{
  parserClass="eaml.parser.EamlParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Eaml"
  psiImplClassSuffix="Impl"
  psiPackage="eaml.psi"
  psiImplPackage="eaml.psi.impl"

  elementTypeHolderClass="eaml.psi.EamlTypes"
  elementTypeClass="eaml.psi.EamlElementType"
  tokenTypeClass="eaml.psi.EamlTokenType"
}

// A program is composed of 1 or more resource definitions
eamlFile 	::= (colorResDef | dimenResDef | boolResDef | integerResDef | stringResDef)*

colorResDef 				::= COLOR   RES_IDEN colorResValue
dimenResDef 				::= DIMEN   RES_IDEN dimenResValue
boolResDef   				::= BOOL    RES_IDEN boolResValue
integerResDef 				::= INTEGER RES_IDEN integerResValue
stringResDef  				::= STRING  RES_IDEN stringResValue

colorResValue 				::= ASSIGNMENT COLOR_LITERAL LTERM 		| L_BR (RES_IDEN ASSIGNMENT COLOR_LITERAL)* R_BR
dimenResValue 				::= ASSIGNMENT DIMEN_LITERAL LTERM 		| L_BR (RES_IDEN ASSIGNMENT DIMEN_LITERAL)* R_BR
boolResValue   				::= ASSIGNMENT BOOL_LITERAL LTERM 		| L_BR (RES_IDEN ASSIGNMENT BOOL_LITERAL)* R_BR
integerResValue 			::= ASSIGNMENT INTEGER_LITERAL LTERM 	| L_BR (RES_IDEN ASSIGNMENT INTEGER_LITERAL)* R_BR
stringResValue  			::= ASSIGNMENT STRING_LITERAL LTERM  	| L_BR (RES_IDEN ASSIGNMENT STRING_LITERAL)* R_BR


